# Generated by Django 3.0.6 on 2020-06-10 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 9, 21, 29, 32, 386551))),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('address1', models.CharField(max_length=80)),
                ('address2', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('donor_type', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
