# Generated by Django 3.0.6 on 2020-06-10 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 9, 21, 34, 26, 101104)),
        ),
    ]
