# Generated by Django 3.0.6 on 2020-06-10 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0004_auto_20200610_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 0, 50, 10, 466351))),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
            },
        ),
        migrations.DeleteModel(
            name='Acknowledge',
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 0, 50, 10, 461368)),
        ),
    ]
