# Generated by Django 3.0.6 on 2020-06-10 07:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_auto_20200610_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='benefactor',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 0, 53, 53, 747128)),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 0, 53, 53, 742125)),
        ),
    ]
