# Generated by Django 3.0.6 on 2020-06-10 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_auto_20200610_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 0, 56, 29, 900060)),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 0, 56, 29, 895060)),
        ),
    ]
