# Generated by Django 3.0.6 on 2020-06-11 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0007_auto_20200610_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 11, 16, 11, 16, 46672)),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 11, 16, 11, 16, 43673)),
        ),
    ]
