# Generated by Django 3.0.6 on 2020-06-15 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0010_auto_20200614_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 14, 16, 36, 351059)),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 14, 16, 36, 341059)),
        ),
    ]
