# Generated by Django 3.0.6 on 2020-06-24 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0011_auto_20200615_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 22, 43, 44, 487140)),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 22, 43, 44, 482140)),
        ),
    ]
