# Generated by Django 3.0.6 on 2020-06-26 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0012_auto_20200623_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 23, 6, 15, 258650)),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 23, 6, 15, 258650)),
        ),
    ]
