# Generated by Django 3.0.6 on 2020-06-27 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0016_auto_20200626_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 22, 39, 23, 367092)),
        ),
        migrations.AlterField(
            model_name='donors',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 22, 39, 23, 367092)),
        ),
    ]
