# Generated by Django 3.0.6 on 2020-06-13 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidelines',
            options={'verbose_name_plural': 'Guideline'},
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 13, 7, 49, 43, 902566)),
        ),
    ]
