# Generated by Django 3.0.6 on 2020-06-13 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0002_auto_20200613_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 13, 8, 56, 44, 570560)),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
