# Generated by Django 3.0.6 on 2020-06-13 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0003_auto_20200613_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 13, 8, 58, 27, 573898)),
        ),
    ]
