# Generated by Django 3.0.6 on 2020-06-15 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0006_auto_20200615_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 15, 14, 17, 34, 663323)),
        ),
    ]
