# Generated by Django 3.0.6 on 2020-06-19 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0007_auto_20200615_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=20)),
                ('total_cases', models.CharField(max_length=250)),
                ('active_cases', models.CharField(max_length=250)),
                ('discharged', models.CharField(max_length=250)),
                ('death_cases', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 9, 42, 14, 894109)),
        ),
    ]
