# Generated by Django 3.0.6 on 2020-06-24 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0010_auto_20200623_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='globalCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40, unique=True)),
                ('country_total_cases', models.CharField(max_length=60, unique=True)),
                ('country_active_cases', models.CharField(max_length=60, unique=True)),
                ('country_recovery', models.CharField(max_length=60, unique=True)),
                ('country_total_deaths', models.CharField(max_length=60, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 22, 43, 44, 492139)),
        ),
    ]
