# Generated by Django 3.0.6 on 2020-06-24 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0011_auto_20200623_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalcases',
            options={'verbose_name_plural': 'Global Cases'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 22, 45, 41, 406573)),
        ),
    ]
