# Generated by Django 3.0.6 on 2020-06-26 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0012_auto_20200623_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcases',
            name='country_active_cases',
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 23, 6, 15, 274237)),
        ),
    ]
