# Generated by Django 3.0.6 on 2020-06-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0014_auto_20200625_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 25, 23, 48, 57, 183872)),
        ),
        migrations.AlterField(
            model_name='globalcases',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]
