# Generated by Django 3.0.6 on 2020-06-27 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0015_auto_20200625_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTotalCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_total_cases', models.CharField(max_length=40)),
                ('global_total_recovery', models.CharField(max_length=40)),
                ('global_total_deaths', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'TOTAL GLOBAL RECORD',
            },
        ),
        migrations.CreateModel(
            name='NigeriaTotalCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nigeria_total_cases', models.CharField(max_length=40)),
                ('nigeria_active_cases', models.CharField(max_length=40)),
                ('nigeria_total_discharge', models.CharField(max_length=40)),
                ('nigeria_total_deaths', models.CharField(max_length=40)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TOTAL NIGERIA RECORD',
            },
        ),
        migrations.RenameModel(
            old_name='cases',
            new_name='NigerianCases',
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 19, 12, 54, 258298)),
        ),
    ]
