# Generated by Django 3.0.6 on 2020-06-27 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0018_auto_20200626_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 23, 6, 28, 725105)),
        ),
    ]
