# Generated by Django 3.0.6 on 2020-06-27 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0020_auto_20200627_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 27, 13, 43, 19, 301332)),
        ),
    ]
